name: 'Send Teams Notification'

description: 'Send a notfication to MS Teams indicating the result of the Github Action Workflow'

inputs:
  description:
    required: true
  workflow:
    required: true
  webhook:
    required: true
  job:
    required: true
  title_override:
    required: false
  steps:
    required: false
  needs:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.description }}
    - ${{ inputs.workflow }}
    - ${{ inputs.webhook }}
    - ${{ inputs.job }}
    - ${{ inputs.title_override }}
    - ${{ inputs.steps }}
    - ${{ inputs.needs }}
